// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "test";    // Network SSID (name)
const char PASS[]     = "test";    // Network password (use for WPA, or use as key for WEP)

void onMessengerChange();
void onOnOffSwitchChange();

String messenger;
bool onOffSwitch;

void initProperties(){

  ArduinoCloud.addProperty(messenger, READWRITE, ON_CHANGE, onMessengerChange);
  ArduinoCloud.addProperty(onOffSwitch, READWRITE, ON_CHANGE, onOnOffSwitchChange);

}

WiFiConnectionHandler conMan("SECRET_WIFI_SSID", "SECRET_WIFI_PASS");
